apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-statefulset
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  serviceName: "{{ .Release.Name }}-headless"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.statefulset.containerPort }}
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "{{ .Values.statefulset.storage.accessMode }}" ]
        resources:
          requests:
            storage: {{ .Values.statefulset.storage.size }}
        storageClassName: "{{ .Values.statefulset.volumeClaimTemplate.storageClassName }}"
